config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks, only: %i[create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'items/search'
  get 'items/keysearch'
  resources :users do
    resources :follow_lists, only: [:index]
    resources :follower_lists, only: [:index]
    resources :bookmarks, only: [:index]
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # Defines the root path route ("/")
  # root "articles#index"
  root "top#first_view"
  delete '/bookmarks', to: 'bookmarks#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :email, presence: true

  has_many :bookmarks
  has_many :books, through: :bookmarks
  # フォローをした、されたの関係
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    if params[:keyword].present?
      # @users = User.where(name: params[:keyword])
      keyword = params[:keyword].downcase
      @users = User.where("LOWER(name) LIKE ?", "%#{keyword}%")
    end
  end

  def show
    @user = User.find(params[:id])
    @books = current_user.books
    @bookmarks = @user.bookmarks
    @user_books = []
    @user.books.each do |book|
      url = "https://api.openbd.jp/v1/get?isbn=%20#{book.isbn}"
      uri = URI(url)
      response = Net::HTTP.get(uri)
      data = JSON.parse(response)
      if data[0].nil? || data[0].values_at('summary')[0].values_at('cover')[0].size == 0
        item = RakutenWebService::Books::Book.search(isbn: book.isbn)
        @user_books.push(item.first.isbn)
        @user_books.push(item.first.title)
        @user_books.push(item.first.author)
        @user_books.push(item.first.large_image_url)
        @user_books.push(item.first.publisher_name)
      else
        @user_books.push(data[0].values_at('summary')[0].values_at('isbn')[0])
        @user_books.push(data[0].values_at('summary')[0].values_at('title')[0])
        @user_books.push(data[0].values_at('summary')[0].values_at('author')[0])
        @user_books.push(data[0].values_at('summary')[0].values_at('cover')[0])
        @user_books.push(data[0].values_at('summary')[0].values_at('publisher')[0])
      end
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#create</h1>
  <p>Find me in app/views/users/create.html.erb</p>
</div>

app/views/users/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#destroy</h1>
  <p>Find me in app/views/users/destroy.html.erb</p>
</div>

app/views/users/index.html.erb
<div class="search-box">
    <%= form_with url: users_path, method: :get, remote: true do |f| %>
      <div class="my-5">
      <div id="selected_user_names"></div>
      <input type="text" id="serch_box" placeholder="名前で検索" class="block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full">
      <div id="selectable-options"></div>
  
      <select id="select" class="hidden">
        <% User.all.each do |user| %>
          <option value=<%= user.id%>>
            <%= user.name %>
          </option>
        <% end %>
        <%= text_field_tag :users, User.all.pluck(:id), class:"hidden" %>
      </select>
    </div>
    <% end %>
</div>


<%= javascript_import_module_tag "user" %>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-center">
      <%= form_with model: @user, local: true do |f| %>
        <div>
        <%= f.label :name, class: '' %>
        <%= f.text_field :name, class: 'mx-auto form-control block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 mb-4' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'mx-auto form-control block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 mb-4' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'mx-auto form-control block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 mb-4' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'mx-auto form-control block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 mb-4' %>
        </div>
        <%= f.submit '登録', class: 'my-3.5 btn btn-primary text-white transition duration-500 ease-in-out transform bg-blue-600 lg:px-10 rounded-xl hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 mb-4' %>
      <% end %>
      <div class='text-center'>
        <%= link_to 'ログインページへ', login_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class= "text-[3vw] ml-5 font-bold">
  <%= @user.name %>
</div>
<div class="flex my-5 ml-5 font-bold">
  <div class="mr-5 p-1">
    <%= link_to "フォロー数: #{@user.followings.count}" ,"#{request.url}/follow_lists" %>
  </div>
  <div class="mr-5 p-1">
    <%= link_to "フォロワー数: #{@user.followers.count}" ,"#{request.url}/follower_lists" %>
  </div>
  <div class= "font-bold">
    <% if current_user.following?(@user) && @user.id != current_user.id %>
      <%= button_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: "bg-red-500 text-white p-1 rounded-xl" %>
    <% elsif @user.id != current_user.id %>
      <%= button_to "フォローする", user_relationships_path(@user.id), method: :post, class: "bg-blue-500 text-white p-1 rounded-xl" %>
    <% end %>
  </div>
</div>
<% if @user_books.present? %>
  <div class="ml-14", style="width:85vw;">
    <% @user_books.flatten.each_slice(5).to_a.each do |n| %>
      <%= render partial: 'shared/item', locals: { n: n } %>
    <% end %>
  </div>
<% end %>