config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks, only: %i[create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'items/search'
  get 'items/keysearch'
  resources :users do
    resources :follow_lists, only: [:index]
    resources :follower_lists, only: [:index]
    resources :bookmarks, only: [:index]
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # Defines the root path route ("/")
  # root "articles#index"
  root "top#first_view"
  delete '/bookmarks', to: 'bookmarks#destroy'
end

app/views/shared/_before_login_header.html.erb
<header class = "absolute flex top-0 h-28 w-screen bg-white">
  <div class = "m-3">
    <%= image_tag 'logo.png',class:"w-28 my-1" %>
  </div>
  <div class = "w-auto absolute right-0 my-8 pr-10 bg-white">
    <ul class = "flex"> 
      <li class = "mx-3.5"> 
        <%= link_to "探す", items_search_path %>
      </li>
      <li> 
        <%= link_to "キーワードから探す", items_keysearch_path %>
      </li>
      <li class = "mx-3.5"> 
        <%= link_to 'ログイン', login_path ,class: 'nav-link' %>
      </li>
    </ul>  
  </div>
</header>

app/views/shared/_favorite.html.erb
  <%= button_to bookmarks_path(isbn: isbn, i: "favorite-button-"),
        id: "js-favorite-button-for-item-#{isbn}", 
        class:"mx-[2.125vw] px-2 py-1 bg-white text-xl text-white font-semibold rounded hover:bg-zinc-200 text-yellow-500",
        style:"width:10vw; font-size:2vw;", 
        method: :post,
        remote: true,
        data: { type: :script } do %>
    Favorite
   <% end %>

app/views/shared/_favorite_button.html.erb
<turbo-frame id="favorite-button-<%= isbn %>">
  <% if  current_user != nil && favorited %>
    <%= render 'shared/unfavorite', { isbn: isbn } %>
  <% elsif current_user != nil %>
    <%= render 'shared/favorite', { isbn: isbn } %>
  <% end %>
</turbo-frame>

app/views/shared/_footer.html.erb
<footer class="bg-gray-200 body-font shadow w-full">
   <div class="md:ml-auto flex flex-wrap text-base justify-center">
    <%= link_to 'プライバシーポリシー', page_path('privacy'),class: "mr-5" %>
    <%= link_to '利用規約', page_path('tos'),class: "mr-5" %>
    <%= link_to "お問い合せ", "https://docs.google.com/forms/d/e/1FAIpQLSc_26brwcDx3ovLvPSBCghP8SryMwUx2GsBUZv0F76I9Rgcww/viewform?usp=sf_link" ,class: "mr-5" %>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class = "absolute top-0 left-0 flex" style = "width: 95vw;">
  <div class= "m-3">
    <%= image_tag 'logo.png',class:"w-28 my-1" %>
  </div>
  <div class = "w-auto absolute right-5 my-8">
    <ul class = "flex"> 
      <li class = "mx-3.5"> 
        <%= link_to "探す", items_search_path %>
      </li>
      <li> 
        <%= link_to "キーワードから探す", items_keysearch_path %>
      </li>
      <li class = "mx-3.5"> 
        <%= link_to "ユーザーを探す", users_path %>
      </li>
      <li class = "mx-3.5"> 
        <%= link_to current_user.name, user_path(current_user) %>
      </li>
      <li>
        <%= button_to 'ログアウト', logout_path, class: 'dropdown-item', method: :delete %>
      </li>
    </ul>
  </div>
</header>

app/views/shared/_item.html.erb
<div class="border-solid border-2 md:border-t-0 border-amber-200 bg-gradient-to-br from-yellow-200 via-yellow-500 to-yellow-200 opacity-50 rounded-3xl hover:opacity-100", style ="height: 35vw;">
    <div class="flex">
      <div>
        <%= image_tag n[3], class:"m-[3.125vw] drop-shadow-2xl",style:"height:30vw; width: auto; max-width: 20vw;"%>
      </div>
      <div class="block">
        <div class= "mx-[2.125vw]">
          <div>
            <p class= "text-white my-[1.525vw] drop-shadow-2xl font-serif" style="font-size:4vw; height:auto;"><%= n[1] %></p>
          </div>
          <p class= "text-white my-[1.525vw] drop-shadow-2xl font-serif" style="font-size:2.5vw;"><%= n[2] %></p>
          <p class= "text-white my-[1.525vw] drop-shadow-2xl font-serif" style="font-size:2.5vw;"><%= n[4] %></p>
          <p class= "text-white my-[1.525vw] drop-shadow-2xl" style="font-size:1.5vw;">ISBN:<%= n[0] %></p>
        </div>
        <div class= "flex">
        <% if current_user.present? %>
          <%= render 'shared/favorite_button', { isbn: n[0], favorited: @books.where(isbn:n[0].to_i).count > 0 } %>
          <%= link_to 'Share', "https://twitter.com/share?url=https://comic-gold-rush.com&text=#{current_user.name}さんは%0a#{n[1]}と出会いました%0a", 
          title: 'Twitter',class:"mx-[2.125vw] px-2 py-1 bg-white text-xl text-yellow-500 font-semibold rounded hover:bg-zinc-200",style:"width:6vw; font-size:1.6vw;", target: '_blank' %>
        <% else %>
        <%= link_to 'Share', "https://twitter.com/share?url=https://comic-gold-rush.com&text=ゲストさんは%0a#{n[1]}と出会いました%0a", 
        title: 'Twitter',class:"mx-[2.125vw] px-2 py-1 bg-white text-xl text-yellow-500 font-semibold rounded hover:bg-zinc-200",style:"width:6vw; font-size:1.6vw;", target: '_blank' %>
        <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_unfavorite.html.erb
  <%= button_to bookmarks_path(isbn: isbn),
               id: "js-favorite-button-for-item-#{isbn}", 
               class:"mx-[2.125vw] px-2 py-1 bg-white text-xl text-white font-semibold rounded hover:bg-zinc-200 text-yellow-500",
               style:"width:13vw; font-size:2vw;", 
               method: :delete,
               remote: true,
               data: { type: :script }  do %>
    UnFavorite
  <% end %>